language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install: travis_retry pip install pytest==2.6.4 $DJANGO_VERSION
env:
  global:
    - PYTHONWARNINGS=all
  matrix:
    - DJANGO_VERSION='Django>=1.5,<1.6'
    - DJANGO_VERSION='Django>=1.6,<1.7'
    - DJANGO_VERSION='Django>=1.7,<1.8'
matrix:
  include:
    - python: 2.7
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "pypy"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
  fast_finish: true
script: python -m pytest
